### ISSUE TITLE
Unable to run bCNC on OSX

### ISSUE THREAD

**Issue by freddykat** [vlachoudis/bCNC#1018]
Hello, 
Been trying for past days to install bCNC on my OSX10.11
Im using python2.7 and installed the adicional packages as per your guide.
When i try to run the bCNC.py I got this error:

`Last login: Sat Oct 27 11:29:25 on ttys000

MBPdeFrederico:~ fredericooliveira$ cd /Users/fredericooliveira/Documents/BCNC/bcnc

MBPdeFrederico:bcnc fredericooliveira$ python bcnc.py

Traceback (most recent call last):
  File "bcnc.py", line 2592, in <module>
    application = Application(tk)
  File "bcnc.py", line 113, in __init__
    self.ribbon = Ribbon.TabRibbonFrame(self)
  File "/Users/fredericooliveira/Documents/BCNC/bCNC/Ribbon.py", line 494, in __init__
    image=Utils.icons["new"],
KeyError: 'new'

MBPdeFrederico:bcnc fredericooliveira$ `

Already tested the Tkinter and it works ok, but i dont seem to get why this happens.
Hope someone can help me out

**Comment by walterwissmann** [comment]
The same issue as here ;-) :
https://github.com/vlachoudis/bCNC/issues/959

**Comment by freddykat** [comment]
> It is a problem with the PNGs
> 
> The same issue as here ;-) :
> #959

Thanks walterwissman,
I've Succesful installed in win but it connects but wont say connected. lol

**Comment by Harvie** [comment]
problem with icons fixed

**Comment by Harvie** [comment]
Hello guys, some offtopic mesage: There is new bCNC version coming and it's really challenging to get it working on Mac OS, because i don't have mac.
Currently the new version resides in https://github.com/koneklaudio/bCNC but i will merge it soon. Can you please help me debug it on MacOS? We are discussing the issues here: https://github.com/vlachoudis/bCNC/issues/591
