### ISSUE TITLE
Strings where there are round brackets b-CNC does not display.

### ISSUE THREAD

**Issue by sfinexer** [vlachoudis/bCNC#1042]
B-cnc instead of a comment displays empty lines.
Ie where there is a block in the 451 line there are only two lines of code, the rest is all empty.
Strings where there are b-CNC parentheses do not display an example:
"G0 Y-0.136 X48.927 (right)"
This is b-CNC error.
[Narisovannyj-glaz V2.cnc.zip](https://github.com/vlachoudis/bCNC/files/2583693/Narisovannyj-glaz.V2.cnc.zip)
![screenshot_20181115_075312](https://user-images.githubusercontent.com/13809436/48531095-d8d9bc80-e8ab-11e8-923b-3a58e5e43ca4.png)

**Comment by Harvie** [comment]
Comments work OK. Problem is with your alphabet. Python 2 cannot support this. I've already told you we know about this in #1006 (also i already have issue #940 on this topic).

No matter how many issues you create it will not change until we move to Python 3.

If you post any issue here, **please do not send g-code containing non-latin letters**. First test on english-only g-code. Otherwise you are wasting my time. The time that could be used to implement python 3 (and therefore cyrilic support) instead.

**Comment by Harvie** [comment]
National alphabets and python3 support should be fixed in latest git master (not in pip release yet). Can you please try?
