### ISSUE TITLE
Code don't adhere to the PEP8 python specifications

### ISSUE THREAD

**Issue by onekk** [vlachoudis/bCNC#1124]
The code don't adhere with the python PEP8 that recommends 4 spaces as a indentation characters.

**Comment by Harvie** [comment]
I prefer tabs and my favourite editor doesn't work very well with spaces. sorry.
I don't want to discus this right now, because this can only lead to holy flamewar without any actual benefit to bCNC project.

But recently i've fixed all files, where there was mixed use of tabs and spaces.
Also i've added travis test that will check all pull requests for mixing of tabs and spaces.

If you need this because of your editor, you can setup "git smudge/clean" to automaticaly replace this on checkout and commit.

**Comment by oddstr13** [comment]
May I ask what your editor of choice is?
Most modern editors can be configured to use 4*space as if it where tab.

**Comment by Harvie** [comment]
Another step of this discussion: Why even use python, when you can use XXXXXXX....
