### ISSUE TITLE
Direction issues

### ISSUE THREAD

**Issue by usajet** [vlachoudis/bCNC#1142]
When I home it goes to the right rear of the cnc. I go to the corner of the work piece and set my zero. But when I do a scan it wants to go to my homing postition and keep going. Any ideas?

**Comment by Harvie** [comment]
What do you mean by "scan"?

**Comment by usajet** [comment]
A trial run of pattern that's going to be milled.

**Comment by Harvie** [comment]
I am not really sure what do you mean.
I don't have homing switches installed, but i believe that scan should happen in work coordinate system rather than in machine coordinates, so it should not really matter if your homing is done right as long as you zero your WCS properly. Can you make some screenshots or video of what exactly you do when that happens?

**Comment by Harvie** [comment]
Is everything OK now?

**Comment by usajet** [comment]
Yes thank you

**Comment by Harvie** [comment]
Just for the record... Do you mind to share what the problem was? In case that somebody experiences the same?

**Comment by usajet** [comment]
It was because of where I  set my zero.
