### ISSUE TITLE
B-cnc stops meeting "!"

### ISSUE THREAD

**Issue by sfinexer** [vlachoudis/bCNC#1151]
B-cnc stops meeting "!" at the beginning of the line. Errors from GRBL no.

**Comment by Harvie** [comment]
Why do you put "!" in your g-code?

**Comment by sfinexer** [comment]
> Why do you put "!" in your g-code?

Is it really prohibited by the documentation on the G-code?

**Comment by Harvie** [comment]
"!" has special meaning in GRBL. You surely can't use it as a comment.

Please stop guessing and read the documentation for linuxcnc g-code and GRBL before creating issues. No you can't just say "im gonna use this g-code because it looks cool". You have to use proper g-code syntax. If you want to use something that is not proper g-code, then you obviously can't use unmodified g-code based tools.

**Comment by sfinexer** [comment]
> "!" has special meaning in GRBL.

What is the importance of GRBL?
I can connect a different controller ...
This code "!" not inconsistent with G-code syntax.

**Comment by Harvie** [comment]
https://github.com/gnea/grbl/wiki/Grbl-v1.1-Commands

**Comment by sfinexer** [comment]
I was wrong.
This is all because in the B-cnc console, I do not see this command in the list of transmitted ones, but only in the buffer.
If I had seen this command in the B-cnc console, I would have no questions!

And without seeing the commands in the list, I assume that there is an error in the B-cnc program.
