### ISSUE TITLE
Plasma Torch Probe During Processing

### ISSUE THREAD

**Issue by CJELLWOOD** [vlachoudis/bCNC#1210]
Is it possible to add a feature for auto probing during gcode processing? 
Skip to 2:30 of this video to see what I mean
https://www.youtube.com/watch?v=hqnqnRb3voU

Probe command sets new zero when switch is hit and raises to set offset. Before each cut

**Comment by Harvie** [comment]
This looks easy. Just connect the probing switch to the probe input of GRBL and add probe+retract g-code before each cut, do not specify Z in the lines that go after that, so it stays in desired height. If you don't want to do this manualy, you can write bCNC plugin to add this on the beginning of each block and make pull request so we can include it in bCNC.


But to be honest, you can already do this using bCNC features. Just use autolevel feature. Only difference is that it will scan the height of your material in advance before you start the job rather than during the job before each cut.

You don't even need that mechanical springy thing nor switch if you setup everything correctly. Since both plasma torch nozzle and steel material are conductive, you can probe by testing electric contact between these two if you know what are you doing (if not 100% sure your wiring is OK, you can run into nasty electrical issues and fry your arduino, so be carefull!)
