### ISSUE TITLE
Work Piece Render

### ISSUE THREAD

**Issue by atrueresistance** [vlachoudis/bCNC#133]
This isn't really an issue, but more of a performance request. It might be possible as is now through the UI..... 

Basically when loading large laser files the UI will become very unresponsive, typically having window's 'Not Responding' gray screen, and sometimes lasting 5 minutes or more... Eventually it will load, and show the tool path. The toolpath for something say 9"x9" with .2mm pixel spacing can be upwards of 1.2 million lines of gcode. Would it be possible to disable toolpath preview and just see a bounding box of work area? Would that increase performance? 

I'm on windows using a 2014 razor blade, so machine specs using to run bCNC are pretty decent. 

Overall, really impressed with bCNC, keep up the good work!

**Comment by vlachoudis** [comment]
@atrueresistance is already there. There are a few checkbuttons on top of the canvas.
The second from the right is for the rapid g0 movements and the third from the right for the cut movements. Uncheck both before loading your file and it will not show the toolpath. Unfortunately you will not be able to see the gcode margins as well, because they are calculated when the path is generated and this is what takes time. Python is not very fast for this things. I could at some point convert this part in C to speed up, but it is a lot of work.
