### ISSUE TITLE
Plugin Text: Text field does not update until you press enter

### ISSUE THREAD

**Issue by BBKACNC** [vlachoudis/bCNC#273]
In the plugin "TEXT" the field "Text to generate" does not update as you type.  

When highlighted the original text stays visible until the user presses "Enter" then the text entered appears.

On a side note: bCNC is a fantastic app.  It is by far the best GRBL sender I have used.  The provision of the editor and plugins just makes it even better.

I'm trying to learn python so that I can create plug ins.

Hat tip to you sir and keep up the good work!

**Comment by Effer** [comment]
Hi @BBKACNC 

it's seems a regression, it was fixed in #167 but it get lost somewhere. It affect only windows OS but I believe can be fixed easily. 

When python is learned have a look at [How to make a plugin](https://github.com/vlachoudis/bCNC/wiki/How%20to%20create%20a%20plugin) and open a pull request. Help is always welcome.
