### ISSUE TITLE
Terminal Window does not allow copy/paste

### ISSUE THREAD

**Issue by twforeman** [vlachoudis/bCNC#283]
If I open the terminal and type $$ to see my current Grbl settings I can select them, but can't copy them. Ctrl-C doesn't copy nor does right-clicking do anything.

It would be nice to be able to copy the terminal output.

This is on Linux, if that matters.

**Comment by vlachoudis** [comment]
It's a bit problematic, since the text field I am using in tkinter behaves like a text editor. So I am disabling to avoid any accidental user editing. Once it is disabled it can not be focused and accept a ctrl-c keystroke. 

However in Linux once you select the text, it is automatically copied on the selection clipboard, and you can paste it anywhere with the middle mouse button.
