### ISSUE TITLE
Feed override doesn't work

### ISSUE THREAD

**Issue by Guenni75** [vlachoudis/bCNC#409]
The feed override doesn't work.
I can see the f... in the terminal output, but it is the same value than before.

**Comment by Guenni75** [comment]
Feed changes only after a G0.

**Comment by Effer** [comment]
Hi @Guenni75 ,
I've made some quick test and there should be a problem after a recent commit. Could you try to run the work with the verbose feed option on? To active use *FEED ON* command in bCNC as you can see below:
![feedon](https://cloud.githubusercontent.com/assets/1007007/17902889/77accca4-6969-11e6-9a22-38eb3a29117c.png)

With this option activated it works correctly (afted some delay due to grbl buffer), without is not working as expected.
