### ISSUE TITLE
Saving Problems

### ISSUE THREAD

**Issue by Guenni75** [vlachoudis/bCNC#418]
After quiting BCNC, changes in Material and Flatten tool settings will not be saved.
I changes the feedrate from 400 to 500 in the Material settings and everytime there is the 400 again.
Same thing in the Flatten tool. Changed things will not be saved.

Something else when i press execute in the Flatten tool for example.
I pressed the execute button with Material feedrate 400.
I deleted the paths in the editor.
Changed the Material feedrate to 500.
After pressing execute in Flatten tool again, the feedrate in the code is 400 again.
After some restarts and pressing new documents severall times, it changes to 500.
I don't know why.

This Problem appears just some times.

**Comment by Effer** [comment]
Hi @Guenni75 ,

I've made some quick test and maybe your issue is hiding something different. 
It's seems like the delete command is not always cleaning correctly the selected elements, that's rise a exception and prevent bCNC to save correctly the settings. It needs more test anyway. If you can find a better way to reproduce the issue it will help.

@onekk proposed me to add another parameter to Flatten tool. It will allow user to override the feed from material. What do you think about it?
