### ISSUE TITLE
Delete elements broke sync between canvas and editor

### ISSUE THREAD

**Issue by Effer** [vlachoudis/bCNC#422]
How to reproduce:
Start bCNC
Go to tools tab
- Close bCNC
- Start again bCNC (this time it should open directly to tool tab)
- Now create something with any tool/plugin (ex Flatten)
- Click and drag a selection area over the produce geometry (no single click)
- Hit canc to delete the geometry
- The geometry should't be erased
- Go to editor tab and see that the related gcode is really missing

See screenshot (not photoshoped!)
![image](https://cloud.githubusercontent.com/assets/1007007/18352421/a99e1f66-75de-11e6-9bfe-ff08e36e86c8.png)

Maybe this is related to both  #417 #418 and #421

**Comment by vlachoudis** [comment]
@Effer I finally found how to reproduce it and it is corrected now. The problem was that the global message that was send from the Delete button if the editor was not yet displayed (at least once) it was not intercepted. So now I am forcing all messages to be send to the master frame which is always there.

**Comment by Effer** [comment]
Good job @vlachoudis, an hard bug to find? I've lost some times looking at code without result. Can you point me at the commit that fix it?

**Comment by vlachoudis** [comment]
https://github.com/vlachoudis/bCNC/commit/3c1f0b1178a79484d1621c4ed5983fef64e8bd8a
