### ISSUE TITLE
Some parameters missing in config files

### ISSUE THREAD

**Issue by Effer** [vlachoudis/bCNC#48]
If **units = 0** (mm) in config file, the parameter is erased at exit fo bCNC. This happen in latest V0.4 relase but I can remember it was saved correctly in old versions.

Also I belive that some parameters could be read (and then saved) from grbl. I refer to feed_max,acceleration and travel that are reported in **$110..112 $120..122** and **$130..132**

**Comment by vlachoudis** [comment]
@Effer its a new feature. The program now deletes from the configuration the lines which are the same as the default one. The reason is to have a cleaner ini file and most important if I change something in the default configuration file it will update it to everybody if they have not touch that feature.

For the moment the feed_max, acceleration, have to be set manually, they are not read from grbl. I have to do it at some time.
