### ISSUE TITLE
If I repeatedly press PAUSE bCNC  generate an error and stop working!

### ISSUE THREAD

**Issue by viewsat** [vlachoudis/bCNC#546]
When I was sending gcode, if I repeatedly press PAUSE, then bCNC will generate an error and stop working! 

use windows 7/32bit 

![bcnc](https://cloud.githubusercontent.com/assets/15762267/24238847/9269a1e2-0fe6-11e7-93e7-6c2856d7078a.png)

**Comment by vlachoudis** [comment]
Here it seems, that the serial is failing. Normally the "!" should be consumed immediately by grbl, so it should not matter how many you push on the grbl buffer. So either is a hardware error (noise on the line), or for some reason grbl is not removing the "!" from the buffer when in Hold state. @chamit any other possible explanation?

**Comment by chamnit** [comment]
@vlachoudis : The '!' character should always be intercepted when received by Grbl. I would need to know more about what the failure is to determine if Grbl is the culprit.

**Comment by vlachoudis** [comment]
@chamnit python is reporting timeout on serial write "!". The only time I saw this exception on hardware errors.

**Comment by chamnit** [comment]
@vlachoudis : Ok. I don't see how Grbl could create a write error on the host side since it just receives the unsynchronized bi-directional data. I would agree that it's likely hardware related or electrical in nature. Also make sure you are not using an Arduino with a CH380 USB-serial chip. These are known to have communication issues.

I just read a thread this morning about a very similar identical issue. It was due to a noisy electrical environment with a spindle under load on the same circuit as the controller and host computer. It was solved by placing the Grbl and the host computer behind a battery backup unit (UPS), while the spindle was connected to the wall receptacle. UPS's have a lot of buffering electronics in them that seemed to help prevent voltage spikes from interfering with communication.

**Comment by viewsat** [comment]
I tried orange pe PC + Armbian last night to perform bCNC, and there seemed to be no mistake.
Arduino with a CH$340G USB-serial chip.

![screenshot_2017-03-24_00-46-55](https://cloud.githubusercontent.com/assets/15762267/24276583/a3749adc-1072-11e7-9130-22c79e9d0bd5.png)


![p_20170324_090206](https://cloud.githubusercontent.com/assets/15762267/24276610/d1325086-1072-11e7-8a35-d9861da827ec.jpg)

**Comment by viewsat** [comment]
But when sending gcode, such as changing the spindle% will have an incorrect action.

**Comment by viewsat** [comment]
I send about 1 million lines of gcode, no problem, except spindle override has occurred wrong action.
use orange pi PC & Armbian .

![screenshot_2017-03-25_08-54-23](https://cloud.githubusercontent.com/assets/15762267/24329610/5dbdfcf4-123e-11e7-8b33-95c68d683a09.png)
