### ISSUE TITLE
Tool  change broken?

### ISSUE THREAD

**Issue by TheArcher1980** [vlachoudis/bCNC#569]
When using the tool change via TLO, the machine first moves the Z-axis down to the tool change location and then to the x/y coordinates (possibly bad?). After successfully probing and setting the TLO, the machine moves back to its x/y start location while in G90 mode and then the Z-axis is moved back up in G90 mode with the z-value after starting. This then crashes the axis into the limit switch, as my machine first moves into the upper left corner with Z raised to the top.

**Comment by TheArcher1980** [comment]
After some more experimentation, it seems this happens if the tool is longer than the probe and the TLO is a positive value. If the TLO is negative, it works just fine.

**Comment by vlachoudis** [comment]
Can you try to change the type of Tool change policy

**Comment by TheArcher1980** [comment]
I found the "bug". When starting a tool change, the work coordinates are saved, it then moves in machine-coordinates to the probe location, probes, and then moves back to the work-coordinates. If the z-axis is at machine 0 and work 0, it would be a negative work value at machine 0 after probing with a tool longer than the probe.

**Comment by vlachoudis** [comment]
Thanks for looking into this. I will have to check when I will be back

**Comment by berkakinci** [comment]
I can confirm this bug on current master branch as of yesterday.
In my case GRBL throws Alarm 2, so no crash.

**Comment by berkakinci** [comment]
After inspecting the code, I see the problem happens around:
https://github.com/vlachoudis/bCNC/blob/8636836c54428df73892d4e54233af5af9ec36a4/CNC.py#L1714
Because I started the program from the home state (0,0,0), it restored to a new (0,0,0) that was outside the machine bounds.

User Workaround:  Before starting the program, jog to a lower Z (Like -40mm).  During the program, the tool remains close to the work, so this is possible but less likely to be a problem at other tool changes.

**Comment by vlachoudis** [comment]
Can you try with the latest master.

**Comment by Harvie** [comment]
closing for lack of response, reopen if needed.
