### ISSUE TITLE
gcode wont fully load

### ISSUE THREAD

**Issue by joshcarz** [vlachoudis/bCNC#680]
I generated some Gcode using fusion 360 for generic GRBL and the file won't fully load on bCNC. Does it work for anyone else? Here is a link to download my Gcode

https://www.dropbox.com/s/gjj7lblww7fm7ir/speedo%20bearing%20carrier%20v2.nc?dl=0

**Comment by joshcarz** [comment]
So I just tried and it does cut everything out. It just doesnt load everything in the GUI and doesnt calculate anything like time remaining after what it can load. Maybe there is a limit to how many lines it can load?

**Comment by vlachoudis** [comment]
This is a repeating question. We should make a FAQ and put it there as first. It is not a loading issue but rather a plotting. Python is slow for rendering and there is a timeout for the display on the top-right corner of the canvas. Increase that so it can show all your code.

**Comment by lalo-uy** [comment]
May be a popup msg warning that timeout have been reached

2017-10-20 17:16 GMT-03:00 Vasilis Vlachoudis <notifications@github.com>:

**Comment by meysamam** [comment]
Set Timeout to max 120

**Comment by nuxeh** [comment]
This has been bugging me for a while, often I had to look for another gcode sender when my gcode wouldn't load. Thanks @meysamam

What is the timeout for..?

**Comment by Harvie** [comment]
canvas is too slow to paint all g-code paths in long g-code files. there is timeout so it does not get stuck forever.
only problem is that g-code is not graphicaly drawn to display. otherwise the code is loaded and can be streamed to machine.
only way to solve this is to implement native code (eg. written in C/C++) g-code canvas and reuse it in bCNC rather than drawing g-code line by line directly from python, which is terribly slow language.

**Comment by nuxeh** [comment]
Indeed, makes perfect sense... Or, even better, Rust :)
