### ISSUE TITLE
Enhancement Request

### ISSUE THREAD

**Issue by ArcAIN6** [vlachoudis/bCNC#743]
I was wondering if it's possible / plans in the future to add a tab / window that displays the lines of G-code, as they are running, with the ability to start running the code at any line. 

In my particular case, i am currently running 3 hours of already run gcode, simply because a breaker tripped. 
Using homing, and G28.1/G28 i was able to retain the origin, and the job can be salvaged, however, the long portion of wasted movements is not particularly enjoyable. 

I think this would be an extremely useful feature, not just for spotting gcode issues on the fly, but would also allow skipping gcode that has already been run in the case of an emergency stop / power failure, etc. 

I believe this feature, or something similar to it is available on commercial softwares bundled with Tormach, and HAAS machines have a feature similar to this.

Thank you

BTW.. I kinda LOVE this software!

**Comment by vlachoudis** [comment]
It was one of my plans to add some debugging features, like run-to, step, continue etc.
Starting from a specific line is problematic, because you would need to execute all the modal commands before. One option I see is to move the gantry to the exact location, and start from the beginning sending all commands except the motion ones (g0,g1,g2,g3) to grbl until the "starting" line.

**Comment by ArcAIN6** [comment]
Thanks.
