### ISSUE TITLE
I can not open last version and legend in previous version

### ISSUE THREAD

**Issue by MARIOBASZ** [vlachoudis/bCNC#942]
I can not open the latest version and the previous version works fine, but this caption appears![image](https://user-images.githubusercontent.com/11743403/44349765-28a71400-a474-11e8-982a-ff94334d90f5.png)

"No module named enum "

Meaning? Does someone happen to you, mainly not being able to use the latest version? solution?

**Comment by Harvie** [comment]
You have to install "enum" module to python:
https://pypi.org/project/enum/

Can be installed using following command `pip2.exe install enum`

It's obviously dependency of STL reader. I've missed this one. However there are several solutions:

  - include it to ./lib/ in bCNC, but that's not possible, since enum is GPLv3+ :-( , maybe we can ask the authors to dual-license
  - it will get fixed by itself once bCNC will run on Python 3, since enum module is included in Python 3 by default
   - STL parser is not needed for slicing, we can write smaller STL parser, i wanted to do that anyway, because current STL parser is more complex than needed, it's on my TODO list (but with very very low priority). Anyway it shouldn't be too hard to eliminate enum dependency altogether to get rid of this problem.

**Comment by Harvie** [comment]
Ok, this is fixed now. But you still need to install numpy.

**Comment by MARIOBASZ** [comment]
I have installed numpy, download from your branch, bcnc does not start

**Comment by Harvie** [comment]
@MARIOBASZ what does it say?

**Comment by MARIOBASZ** [comment]
numpy I have it installed before, I think you need it is necessary to use the camera
C: \ Users \ User \ Desktop \ Python27 \ Lib \ site-packages
I do not know why, but it does not start

**Comment by Harvie** [comment]
@MARIOBASZ so it does still complain about numpy even when it's installed?

**Comment by MARIOBASZ** [comment]
@Harvie, mi problema es que BCNC no se inicia, parece que inicia y cierra BCNC y la ventana de python

**Comment by Harvie** [comment]
launch it from commandline, or othervise get the output of it.
eg.: put pause at the end of bCNC.bat

```
@echo off
set DIR=%~dp0
set PYTHONPATH=%DIR%lib;%DIR%plugins;%PYTHONPATH%
start python "%DIR%bCNC.py"
pause
```

or maybe

```
@echo off
set DIR=%~dp0
set PYTHONPATH=%DIR%lib;%DIR%plugins;%PYTHONPATH%
python "%DIR%bCNC.py"
pause
```

**Comment by Harvie** [comment]
Try installing Pillow (also known as PIL) module

**Comment by MARIOBASZ** [comment]
Here it is already late, tomorrow I will try, thank you very much!

**Comment by MARIOBASZ** [comment]
Hello, I downloaded Pillow and the problem continues. From the command line I followed your suggestion, this legend appears:
image=Utils.icons ["new"]
KeyError: 'new'
![image](https://user-images.githubusercontent.com/11743403/44486766-e3791280-a62a-11e8-9925-ae536785ab91.png)

I hope it is solved and download the version with your latest advances

**Comment by alk1913** [comment]
helloi think that is something related with the icons extension.
try this
[bCNC-master (22).zip](https://github.com/vlachoudis/bCNC/files/2312341/bCNC-master.22.zip)

**Comment by Harvie** [comment]
@alk1913 did you converted the file format, or just changed the extension?

**Comment by alk1913** [comment]
Hello,i change the file format

**Comment by Harvie** [comment]
I've converted images back to GIFs and commited the changes...

**Comment by MARIOBASZ** [comment]
Thanks, it's already open
